module SkelCalc where

-- Haskell module generated by the BNF converter

import AbsCalc
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x


