module AbsFun where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Program =
   Prog [Def]
  deriving (Eq,Ord,Show)

data Def =
   Df Ident [Ident] Exp
  deriving (Eq,Ord,Show)

data Exp =
   EVar Ident
 | EInt Integer
 | EApp Exp Exp
 | EPlus Exp Exp
 | EMinus Exp Exp
 | ELess Exp Exp
 | ECond Exp Exp Exp
 | EAbs Ident Exp
  deriving (Eq,Ord,Show)

